# Generated by Django 5.0.2 on 2024-05-29 12:16

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_options_contentblock_image_big_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image_top',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[1080, 450], upload_to='news/images', verbose_name='Картинка вверху статьи (1080x450)'),
        ),
    ]
