# Generated by Django 5.0.2 on 2024-04-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_callbackform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackform',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='callbackform',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='callbackform',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
