# Generated by Django 5.0.2 on 2024-04-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_callbackform_email_alter_callbackform_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackform',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='email'),
        ),
    ]
