# Generated by Django 5.0.2 on 2024-05-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_callbackform_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackform',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Обработана'),
        ),
    ]
