# Generated by Django 5.0.2 on 2024-02-21 10:03

import django.db.models.deletion
import django_ckeditor_5.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, help_text='Если не заполнено, создается на основе поля Назавание', max_length=255, null=True, verbose_name='ЧПУ')),
                ('show_at_equipment', models.BooleanField(default=True, verbose_name='Вывод в меню')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('is_arrive', models.BooleanField(default=False, verbose_name='В пути?')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('image_main', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[800, 600], upload_to='shop/product/images')),
                ('image_alt', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[800, 600], upload_to='shop/product/images')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, help_text='Если не заполнено, создается на основе поля Назавание', max_length=255, null=True, verbose_name='ЧПУ')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('html_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='SEO текст')),
                ('wb_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Wb')),
                ('ozon_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Ozon')),
                ('file', models.FileField(blank=True, null=True, upload_to='shop/product/files', verbose_name='Файл инструкции')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='ProductComplect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('label', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('value', models.CharField(max_length=255, null=True, verbose_name='Значение')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[100, 100], upload_to='shop/product/images')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complects', to='shop.product')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектации',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('value', models.CharField(max_length=255, null=True, verbose_name='Значение')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shop.product')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[800, 600], upload_to='shop/product/images')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Доп. изображение товара',
                'verbose_name_plural': 'Доп. изображения товара',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, help_text='Если не заполнено, создается на основе поля Назавание', max_length=255, null=True, verbose_name='ЧПУ')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[420, 420], upload_to='shop/category/images')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('html_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='SEO текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='shop.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('order_num',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.subcategory'),
        ),
    ]
