# Generated by Django 5.0.2 on 2024-02-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image_product_is_new_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название1'),
        ),
    ]
