# Generated by Django 5.0.2 on 2024-03-13 05:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_producttextblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='html_content',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
