# Generated by Django 5.0.2 on 2024-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_embed_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код видео'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ'),
        ),
    ]
