# Generated by Django 5.0.2 on 2024-06-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_youtube_embed_code_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул'),
        ),
    ]
