# Generated by Django 5.0.2 on 2024-10-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_price_wb_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена в карточке'),
        ),
    ]
